<?php
 /**
 * Implementation of hook_install().
 */
function pathautodefault_install() {
$weight = db_select('system', 's')
              ->fields('s', array('weight'))
              ->condition('name', '[pathauto]', '=')
              ->execute()
              ->fetchField();

  db_update('system')
    ->fields(array('weight' => $weight +1))
    ->condition('name', '[pathautodefault]', '=')
    ->execute();
}
 